version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cosre_db
  backend:
    build: ./backend
    ports: ["8000:8000"]
    depends_on: [db]
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/cosre_db
  frontend:
    build: ./frontend
    ports: ["3000:5173"]
    depends_on: [backend]
